# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FormView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FormView

  pod 'SwiftDate'
  pod 'ZLPhotoBrowser'
  pod 'SDWebImage'
  pod 'IQKeyboardManagerSwift'
  target 'FormViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FormViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
